"use strict";

var FPS_LIMIT = 60;

var APPROACH_DISTANCE = 1;
var MINIMAL_VOLUME = 8;
var MIN_VELOCITY = 0.1;

var DEFAULT_ORB_WIDTH_SEGMENTS = 22;
var DEFAULT_ORB_HEIGHT_SEGEMNTS = 22;
var DEFAULT_ORB_COLOR = 0x444444;

var RESTITUTION_WALL = 0.9;
var RESTITUTION_ORB = 0.9;

var WALL_WIDTH = 2;
var WALL_LENGTH = 1500;
var WALL_HEIGHT = 1;

var INITIAL_CAMERA_POSITION_Z = 1860;
var CAMERA_LOOKAHEAD = 30;